DROP TABLE IF EXISTS MP3;
DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE MP3 (
  ID        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  NAME      TEXT                              NOT NULL,
  AUTHOR_ID INT                               NOT NULL,
  UNIQUE (NAME, AUTHOR_ID)
    ON CONFLICT REPLACE
);

CREATE TABLE AUTHOR (
  ID   INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  NAME TEXT                              NOT NULL,
  UNIQUE (NAME)
    ON CONFLICT IGNORE
);

INSERT INTO AUTHOR (NAME) VALUES ('Prodigy');
INSERT INTO AUTHOR (NAME) VALUES ('Rammstein');

INSERT INTO MP3 (AUTHOR_ID, NAME) VALUES (1, 'Diesel power');
INSERT INTO MP3 (AUTHOR_ID, NAME) VALUES (2, 'Reise, reise');
INSERT INTO MP3 (AUTHOR_ID, NAME) VALUES (2, 'America');